version: 2
updates:
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: weekly
- package-ecosystem: npm
  open-pull-requests-limit: 10
  directory: /
  schedule:
    interval: weekly
